### PR TITLE
Create copyright

### PR DESCRIPTION
**Pull request by sravyamks**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build was run locally and any changes were pushed
- [ ] Lint has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by pzakha — COMMENTED** [review]
Is it meant to go into `6.0/release`? FYI, as I mentioned in the master review, those changes will not actually make it to the package until we manually push the new package to artifactory and update https://github.com/delphix/linux-pkg/blob/master/packages/td-agent-prebuilt/config.sh#L20.

**Comment by sravyamks** [comment]
I kept updated the review from stage to release as the branching for release is already complete. But, now that you mentioned about the package i recollect why I ignored this review. Do we have any plans on updating the code to not use that pr-built package? Also, What could be the effort included in doing so?

**Comment by pzakha** [comment]
@sravyamks I'm currently working on a big refactor of Linux-pkg (https://jira.delphix.com/browse/TOOL-9778), and after it is done we can move off the pre-built package. It will likely take anywhere from 1-3 months for this work to be completed though.

**Comment by sravyamks** [comment]
Cool. Is this work planned for any of the backports as of now?

**Comment by pzakha** [comment]
Yeah, the work will be backported to all active branches.

**Comment by sravyamks** [comment]
Thank you. I am just closing this pull request.

**Review by pzakha — APPROVED** [review]

**Review by prakashsurya — APPROVED** [review]

**Pull request merged**
